[package]
name = "find-the-relation"
version = "0.1.0"
authors = ["Søren Fuglede Jørgensen <>", "Janus <janus@insignificancegalore.net>"]
edition = "2018"


[dependencies]
dtoa = "0.4.6"
num = "0.3.1"

[profile.release]
lto = true
opt-level = "s"
