name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download wasm-pack
        run: |
          wget https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz
          tar --strip-components=1  -zxvf wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz

      - name: Build WASM project
        run: ./wasm-pack build

      - name: Build frontend
        run: |
          cd www
          npm install
          npm run build

      - name: Publish to GitHub pages
        run: |
          git clone https://fuglede:$TOKEN@github.com/fuglede/find-the-relation.git --branch gh-pages --single-branch gh-pages
          cd gh-pages
          git rm *
          cp ../www/dist/* .
          touch .nojekyll
          git config --local user.email "github@fuglede.dk"
          git config --local user.name "Søren Fuglede Jørgensen"
          git add .
          git commit -m "Publish static files" --amend
          git push -f
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
